# -*- coding: utf-8 -*-
"""AULA3SUB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PazZsr26hetvR4146dH_edLp27TU_W4N
"""

# ETE PORTO DIGITAL
# DISCIPLINA: LPC1
# PROFESSOR: CLOVES
# ALUNO: ALLANA

print('olá, ETE PORTO DIGITAL!')